//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// BeginBar_res.rc

#define IDD_BUTTONS                         1
#define IDD_MENU                            2
#define IDD_ITEM                            3

#define IDS_ACTION_0000                     500
#define IDS_ACTION_0001                     501
#define IDS_ACTION_0002                     502
#define IDS_ACTION_0003                     503
#define IDS_ACTION_0004                     504
#define IDS_ACTION_0005                     505
#define IDS_ACTION_0006                     506
#define IDS_ACTION_0007                     507
#define IDS_ACTION_0008                     508
#define IDS_ACTION_0009                     509
#define IDS_NEWBUTTON                       600
#define IDS_EXITBEGINBAR                    601
#define IDS_EXITWINDOWS                     602
#define IDS_REBOOT                          603
#define IDS_LOGOFF                          604
#define IDS_RECENTS                         605
#define IDS_FAVORITES                       606
#define IDS_PROGRAMS                        607
#define IDS_BEGIN                           608
#define IDS_SELECTFILE                      609
#define IDS_SELECTICON                      610
#define IDS_INPUTACTION                     611
#define IDS_INPUTPATH                       612
#define IDS_INPUTCSIDL                      613
#define IDS_INPUTITEMNAME                   614
#define IDS_NONE                            615
#define IDS_SEP                             616
#define IDS_INDENT                          617
#define IDS_DELETEBUTTON                    618
#define IDS_QUERYDELETE                     619
#define IDS_BEGINBAR                        620
#define IDS_ALLFILES                        621
#define IDS_EMPTY                           622
#define IDS_EXPAND                          623
#define IDS_NOEXPAND                        624
#define IDS_COMPUTER                        625
#define IDS_CONTROLPANEL                    626
#define IDS_DOCUMENTS                       627
#define IDS_NEEDSITEM                       628
#define IDS_CSIDL_0x0000                    1000
#define IDS_CSIDL_0x0001                    1001
#define IDS_CSIDL_0x0002                    1002
#define IDS_CSIDL_0x0003                    1003
#define IDS_CSIDL_0x0004                    1004
#define IDS_CSIDL_0x0005                    1005
#define IDS_CSIDL_0x0006                    1006
#define IDS_CSIDL_0x0007                    1007
#define IDS_CSIDL_0x0008                    1008
#define IDS_CSIDL_0x0009                    1009
#define IDS_CSIDL_0x000A                    1010
#define IDS_CSIDL_0x000B                    1011
#define IDS_CSIDL_0x000C                    1012
#define IDS_CSIDL_0x000D                    1013
#define IDS_CSIDL_0x000E                    1014
#define IDS_CSIDL_0x000F                    1015
#define IDS_CSIDL_0x0010                    1016
#define IDS_CSIDL_0x0011                    1017
#define IDS_CSIDL_0x0012                    1018
#define IDS_CSIDL_0x0013                    1019
#define IDS_CSIDL_0x0014                    1020
#define IDS_CSIDL_0x0015                    1021
#define IDS_CSIDL_0x0016                    1022
#define IDS_CSIDL_0x0017                    1023
#define IDS_CSIDL_0x0018                    1024
#define IDS_CSIDL_0x0019                    1025
#define IDS_CSIDL_0x001A                    1026
#define IDS_CSIDL_0x001B                    1027
#define IDS_CSIDL_0x001C                    1028
#define IDS_CSIDL_0x001D                    1029
#define IDS_CSIDL_0x001E                    1030
#define IDS_CSIDL_0x001F                    1031
#define IDS_CSIDL_0x0020                    1032
#define IDS_CSIDL_0x0021                    1033
#define IDS_CSIDL_0x0022                    1034
#define IDS_CSIDL_0x0023                    1035
#define IDS_CSIDL_0x0024                    1036
#define IDS_CSIDL_0x0025                    1037
#define IDS_CSIDL_0x0026                    1038
#define IDS_CSIDL_0x0027                    1039
#define IDS_CSIDL_0x0028                    1040
#define IDS_CSIDL_0x0029                    1041
#define IDS_CSIDL_0x002A                    1042
#define IDS_CSIDL_0x002B                    1043
#define IDS_CSIDL_0x002C                    1044
#define IDS_CSIDL_0x002D                    1045
#define IDS_CSIDL_0x002E                    1046
#define IDS_CSIDL_0x002F                    1047
#define IDS_CSIDL_0x0030                    1048
#define IDS_CSIDL_0x0031                    1049

#define ID_BUTTON_ADD                       100
#define ID_BUTTON_DELETE                    101
#define ID_BUTTON_PROPERTY                  102
#define ID_BAR_PROPERTY                     103
#define ID_HORIZONTAL                       104
#define ID_VERTICAL                         105
#define ID_ACTION_FIRST                     200
#define ID_EXITAPP                          200
#define ID_EXITWIN                          201
#define ID_LOGOFF                           202
#define ID_ACTION_LAST                      203
#define ID_REBOOT                           203

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     204
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
